[project]
name = "ai-video-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.7",
    "mlx-whisper>=0.4.1",
    "yt-dlp>=2024.12.3",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.8.2",
]
